modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL=""
license="The Unlicense"
[[mods]]
	modId="bettersounds"
	version="${file.jarVersion}"
	displayName="Better Sounds"
	displayURL=""
	authors="Brycey92"
	description="Adds better sounds ;)"
	logoFile="logo.png"

[[dependencies.bettersounds]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1,)"
    ordering="NONE"
    side="BOTH"